
--2.Create View pembiayaan
 CREATE VIEW DBO.V_STG_PEMBIAYAAN AS
SELECT
    DISTINCT A.CRTDATE AS TBCRTDT,
    A.UPDDATE AS TBMDFDT,
    A.CIFID TBCIFID,
    A.ACCNBR TBACCNBR,
    COALESCE(A.IDFACILITY,
    A.ACCNBR) TBIDFACILITY,
    A.CIFNM TBCIFNM,
    COALESCE(C.SURENM,
    D.COMPNM) TBSURENM,
    B.FULLNM TBFULLNM,
    COALESCE(C.ADDR,
    D.ADDR) TBADDR,
    C.LASTEDUID TBLASTEDUID,
    C.BRTPLACE TBBRTPLACE,
    C.SEX TBSEX,
    B.NPWP TBNPWP,
    (
    SELECT
        PARMNMOTH
    FROM
        CFG_PARM
    WHERE
        PARMID = C.OWNID
        AND PARMGRP = '824') TBOWNID,
    N.BANKREL TBBANKREL,
    C.COUNTRYID TBCOUNTRYID,
    C.TYPEID TBTYPEID,
    C.IDNBR TBIDNBR,
    CAST(VARCHAR_FORMAT(C.BRTDT,
    'YYYY-MM-DD') AS VARCHAR(20)) AS TBBRTDT,
    C.MARRIAGEID TBMARRIAGEID,
    C.IDNBRCPL TBIDNBRPCL,
    C.CPLNAME TBCPLNAME,
    CAST(VARCHAR_FORMAT(C.CPLBRTHDT,
    'YYYY-MM-DD') AS VARCHAR(20)) AS TBCPLBRTHDT,
    C.DEALASST TBDEALASST,
    COALESCE(C.LNGBMPK,
    D.LNGBMPK) TBLNGBMPK,
    COALESCE(C.PASSBMPK,
    D.PASSBMPK) TBPASSBMPK,
    C.MOTHRNM TBMOTHRNM,
    B.BRANCHID TBBRANCHID,
    'C' TBOPDATA,
    NULL AS TBGRPUSH,
    --kolomnya belum ada
 A.ACCSTS AS TBSTSPBY,
    (
    SELECT
        PARMNMOTH
    FROM
        CFG_PARM
    WHERE
        PARMID = G.CTGBUSSXBRL
        AND PARMGRP = '810') AS TBCTGBUSSXBRL,
    (
    SELECT
        PARMNMOTH
    FROM
        CFG_PARM
    WHERE
        PARMID = G.CTGFRTFOLIO
        AND PARMGRP = '815') AS TBCTGFRTFOLIO,
    (
    SELECT
        PARMNMOTH
    FROM
        CFG_PARM
    WHERE
        PARMID = G.SRCFUND
        AND PARMGRP = '833') AS TBSMBRDN,
    (
    SELECT
        PARMNMOTH
    FROM
        CFG_PARM
    WHERE
        PARMID = N.CITYNM
        AND PARMGRP = '903') TBCITYNM,
    G.ECOSECXBRL TBECOSECXBRL,
    (
    SELECT
        PARMNMOTH
    FROM
        CFG_PARM
    WHERE
        PARMID = G.CTGBUSSXBRL
        AND PARMGRP = '810') AS TBCTGBUSSXBRLUMKM,
    '947' TBSRCFUND,
    '1' AS TBTYPEINVEST,
    D.CERTNO TBCERTNO,
    D.COMPNM TBCOMPNM,
    D.COMTYPE TBCOMTYPE,
    D.ADDRBUILD TBADDRBUILD,
    D.CERTNO TBCERTNOAKTA,
    CAST(VARCHAR_FORMAT(D.DTBUILD,
    'YYYY-MM-DD') AS VARCHAR(20)) AS TBDTBUILD,
    N.LASTCERTNO TBLASTCERTNO,
    CAST(VARCHAR_FORMAT(N.LASTCERTDT,
    'YYYY-MM-DD') AS VARCHAR(20)) AS TBLASTCERTDT,
    N.NOTELP TBNOTELP,
    N.NOHP TBNOHP,
    O.EMAIL TBEMAIL,
    (
    SELECT
        PARMNM
    FROM
        CFG_PARM
    WHERE
        PARMID = N.KELNM
        AND PARMGRP = '906') TBKELNM,
    (
    SELECT
        PARMNM
    FROM
        CFG_PARM
    WHERE
        PARMID = N.KECNM
        AND PARMGRP = '904') TBKECNM,
    N.POSTALCODE TBPOSTALCODE,
    E.JOBID TBJOBID,
    E.COMNMJOB TBCOMNMJOB,
    E.ADDRJOB TBADDRJOB,
    C.AMTGRSSAL TBAMTGRSSAL,
    C.MAINSALID TBMAINSALID,
    CASE
        WHEN C.INSURED IS NULL THEN 0
        ELSE C.INSURED
    END AS TBINSURED,
    COALESCE(C.LNGBMPK,
    D.LNGBMPK) TBLGRBMPK,
    D.GOPBLC TBGOPBLC,
    0 AS TBAMTPROJ,
    --khusus mst_financing
(
    SELECT
        MAX(FUNC) FUNC
    FROM
        MST_CIFSTAFF
    WHERE
        CIFID = A.CIFID) AS TBFUNC,
    (
    SELECT
        MAX(STSREC) STSREC
    FROM
        MST_CIFSTAFF
    WHERE
        CIFID = A.CIFID) AS TBSTSREC,
    100 TBPGSMLK,
    (
    SELECT
        PARMNMOTH
    FROM
        CFG_PARM
    WHERE
        PARMID = G.KINDFINXBRL
        AND PARMGRP = '812') AS TBKINDFINXBRL,
    A.CONTRACTNO TBCONTRACTNO,
    CAST(VARCHAR_FORMAT(A.AGREEDT,
    'YYYY-MM-DD') AS VARCHAR(20)) AS TBAGREEAPRDT,
    I.NEWCONTRACTNO TBOLDCONTRACTNO,
    CAST(VARCHAR_FORMAT(I.OLDSTRTDT,
    'YYYY-MM-DD') AS VARCHAR(20)) AS TBOLDSTRTDT,
    CASE
        WHEN (
        SELECT
            COUNT(1)
        FROM
            QARD_ADENDUM
        WHERE
            ACCNBR = A.ACCNBR) = 0 THEN '0'
        ELSE (
        SELECT
            COUNT(1)
        FROM
            QARD_ADENDUM
        WHERE
            ACCNBR = A.ACCNBR)
    END AS TBBR,
    CAST(VARCHAR_FORMAT(A.OPENDT,
    'YYYY-MM-DD') AS VARCHAR(20)) AS TBOPENDT,
    CAST(VARCHAR_FORMAT(A.STRTDT,
    'YYYY-MM-DD') AS VARCHAR(20)) AS TBSTRTDT,
    CAST(VARCHAR_FORMAT(A.DUEDT,
    'YYYY-MM-DD') AS VARCHAR(20)) AS TBDUEDT,
    CASE
        WHEN A.APPLID = '09' THEN 'B'
        WHEN A.APPLID = '08' THEN 'S'
        WHEN A.APPLID IN ('05',
        '06',
        '11') THEN 'P'
        ELSE NULL
    END TBSKMPBY,
    CASE
        WHEN A.APPLID = '11' THEN '100'
        ELSE NULL
    END AS TBJNSAKAD,
    CASE
        WHEN A.APPLID IN ('09',
        '11') THEN 'NMT'
        ELSE NULL
    END AS TBMTDBGHSL,
    --JIKA MUDHRABAH 'NMT' ELSE NULL
    --CAST(VARCHAR_FORMAT(A.AGREEAPRDT, 'YYYY-MM-DD') AS VARCHAR(20)) AS TBTGLCAIR,
(
    SELECT
        CAST(VARCHAR_FORMAT(MAX(TXDATE),
        'YYYY-MM-DD') AS VARCHAR(20)) MAX_TXDATE
    FROM
        HIST_TX_PBY HTP
    WHERE
        HTP.TXCODE = 199
        AND HTP.ACCNBR = A.ACCNBR) AS TBTGLCAIR,
    VARCHAR_FORMAT(ROUND(A.EQRATE, 2),
    '990.99') TBEQRATE,
    0 TBRBH,
    G.TYPEFINXBRL TBCHARSID,
    G.TYPEUSEDXBRL TBTYPEUSEDXBRL,
    (
    SELECT
        PARMNMOTH
    FROM
        CFG_PARM
    WHERE
        PARMID = G.ORIUSEDXBRL
        AND PARMGRP = '830') TBORIUSEDXBRL,
    P.CCYID TBCCYID,
    G.GVRMENTPRGM TBGVRMENTPRGM,
    G.SKUR TBSKUR,
    G.LOCXBRL TBLOCXBRL,
    5 TBDefault,
    VARCHAR_FORMAT(COALESCE(ROUND(R.OLDEQRATE, 2),
    ROUND(A.EQRATE, 2)),
    '990.99') TBEQRATEAWL,
    VARCHAR_FORMAT(ROUND(A.EQRATE, 2),
    '990.99') TBEQRATEBLN,
    A.QUALRPT TBQUALRPT,
    COALESCE(H.AMOUNT,
    A.PLAFOND) TBPLAFOND,
    A.PLAFOND TBPLFONDIDR,
    --data diturunkan berdasarkan akad (bukan hanya dari table Qardh)" amtbal ato plafond
 0 TBPLFONDVLS,
    (
    SELECT
        PARMNMOTH
    FROM
        CFG_PARM
    WHERE
        PARMID = G.RATINGINST
        AND PARMGRP = '816') TBRATINGINST,
    (
    SELECT
        PARMNMOTH
    FROM
        CFG_PARM
    WHERE
        PARMID = G.RATINGVAL
        AND PARMGRP = '301') TBRATINGVAL,
    CAST(VARCHAR_FORMAT(G.RATINGDT,
    'YYYY-MM-DD') AS VARCHAR(20)) AS TBRATINGDT,
    '0' AS TBTKOVR,
    --khusus mst_financing
 A.QUALCD TBQUALRPTKD,
    CAST(VARCHAR_FORMAT(A.QUALDT,
    'YYYY-MM-DD') AS VARCHAR(20)) AS TBQUALDT,
    G.PUJAMIN TBPUJ,
    G.SBBMCT TBKDSBMCT,
    H.PERIOD AS TBPERIODFIN,
    CASE
        WHEN A.APPLID = '08' THEN A.AMTMARGIN
        ELSE 0
    END AS TBAMTMARGIN,
    CASE
        WHEN A.APPLID = '08' THEN L.AKMDEPR
        ELSE 0
    END AS TBAKMDEPR,
    CASE
        WHEN A.APPLID = '08' THEN A.AMTCKPN
        ELSE 0
    END AS TBPPAP,
    0 AS TBADVANCE,
    --khusus mst_financing
 A.PLAFOND TBPLAFONDNEWIDR,
    0 TBPLAFONDNEWVLS,
    A.AMTBAL TBREALSIDR,
    0 TBREALSVLS,
    A.AMTBAL TBHP,
    --sisa_margin dari mana
(A.AMTMARGIN - A.ACUMPAYMGN) TBMRGTGH,
    CASE
        WHEN A.ACCSTS = 9 THEN 0
        ELSE A.AMTBAL
    END TBAMTBAL,
    CASE
        WHEN A.ACCSTS = 9 THEN 0
        ELSE A.AMTBAL
    END TBAMTBALIDR,
    0 TBAMTBALVLS,
    A.ACUMACCRU + A.ACUMPYAD AS TBACUMACCRU,
    CASE
        WHEN A.ACCSTS = 9 THEN 0
        ELSE A.AMTBAL
    END TBJML,
    A.PENALTYPRD TBDENDA,
    --diqardh blm ada kolom penalty
 A.AMTPCLOUT TBAMTPCLOUT,
    A.AMTMGNOUT TBAMTMGNOUT,
    A.DAYPASTDUE TBDAYPASTDUE,
    A.DAYPASTDUEPCL TBPCLOUTDAY,
    A.DAYPASTDUEMGN TBMGNOUTDAY,
    COALESCE(FREK.FREKTUNGGAKAN,
    0) AS TBFRQTGK,
    --(count)
 A.AMTCKPN TBAMTCKPN,
    J.RESTRUCTWAY TBRESTRUCTWAY,
    J.AMTLOSS TBRGRESTRUC,
    --blm ada kolomny
 A.RESTRUCTCOUNT TBRESTRUCTCOUNT,
    CAST(VARCHAR_FORMAT(J.RESTRUCTDT,
    'YYYY-MM-DD') AS VARCHAR(20)) AS TBRESTRUCTDTAWL,
    CAST(VARCHAR_FORMAT(A.RESTRUCTDT,
    'YYYY-MM-DD') AS VARCHAR(20)) AS TBRESTRUCTDTAHR,
    H.STSCOND TBACCSTSKD,
    CAST(VARCHAR_FORMAT(A.STSDT,
    'YYYY-MM-DD') AS VARCHAR(20)) AS TBACCSTSTGL,
    A.ACCNBR TBACCNBRREF,
    (
    SELECT
        PARMNMOTH
    FROM
        CFG_PARM
    WHERE
        PARMID = M.ASSETTYPEXBRL
        AND PARMGRP = '817') AS TBASSETTYPEXBRL,
    CAST(VARCHAR_FORMAT(K.STRDT,
    'YYYY-MM-DD') AS VARCHAR(20)) AS TBSTRTDTASET,
    M.CCYID TBCCYIDASET,
    K.BOOKVALUE TBBOOKVALUE,
    L.OBJECTAGE TBAMTDEPPRD,
    CASE
        WHEN A.APPLID = '08' THEN L.DEPRMTD
        ELSE 0
    END AS TBDEPRMTD,
    A.PLAFOND TBNILKTK,
    CASE
        WHEN A.APPLID = '09' THEN H.FLEXAMT
        ELSE 0
    END AS TBFLEXAMTCOM,
    0 AS TBFLEXAMTUNCOM,
    CASE
        WHEN A.PLAFOND < A.FLEXAMT THEN 0
        ELSE A.PLAFOND
    END AS TBAGUNANKRD,
    A.FLEXAMT TBAGUNANLGRTRK,
    CASE
        WHEN A.QUALCD = 1 THEN A.AMTCKPNPSAK
        ELSE 0
    END AS TBAMTCKPNPSAKB,
    CASE
        WHEN (A.QUALCD = 2
        OR A.QUALCDREST = 1) THEN A.AMTCKPNPSAK
        ELSE 0
    END AS TBAMTCKPNPSAKKB,
    CASE
        WHEN (A.QUALCD IN (3,
        4,
        5)
        OR A.QUALCDREST = 2) THEN A.AMTCKPNPSAK
        ELSE 0
    END AS TBAMTCKPNPSAKTB,
    CAST(VARCHAR_FORMAT(H.DUEDT,
    'YYYY-MM-DD') AS VARCHAR(20)) AS TBFREKADDJT,
    A.AMTBAL TBAMTASL,
    H.NOTE TBNOTE,
    NULL AS TBDEPRDT,
    A.SGMNID TBSGMNID,
    H.CONTRACTNO AS TBCONTRACTNOFAS,
    A.OTHDEST AS TBOTHDEST,
    A.OTHSRC AS TBOTHSRC,
    A.TYPEREP AS TBTYPEREP,
    A.AMTBAL AS TBOSTBAL,
    A.SGMNID AS TBSEGMENT,
    0 AS TBMGNEFCTV,
    0 AS TBAMORATRIB,
    0 AS TBACUMACRUPSAK,
    A.ACUMAMOR + A.AMOROUT AS TBACUMACRUATRIB,
    PDPT.DISC AS TBPDPTDISC,
    PDPT.ADM AS TBPDPTADM,
    A.ACUMPAYMGN AS TBPDPTMGN,
    0 AS TBPDPTMGNPSAK,
    0 AS TBPDPTMGNWO,
    0 AS TBPDPTPCLWO
FROM
    MST_QARDH A
LEFT JOIN MST_CIF B ON
    A.CIFID = B.CIFID
LEFT JOIN MST_CIFPERSNL C ON
    B.CIFID = C.CIFID
LEFT JOIN MST_CIFCOM D ON
    B.CIFID = D.CIFID
LEFT JOIN (
    SELECT
        DISTINCT CIFID,
        MAX(JOBID) JOBID,
        MAX(COMNMJOB) COMNMJOB,
        MAX(ADDRJOB) ADDRJOB,
        MAX(DTCRT) DTCRT
    FROM
        MST_CIFJOB
    WHERE
        AKTIFJOB = 1
    GROUP BY
        CIFID) E ON
    B.CIFID = E.CIFID
LEFT JOIN CFG_LBUSID G ON
    A.ACCNBR = G.ACCNBR
LEFT JOIN FIN_FACILITY H ON
    A.IDFACILITY = H.IDFACILITY
LEFT JOIN (
    SELECT
        ACCNBR,
        '' AS NEWCONTRACTNO,
        MAX(OLDSTRTDT) OLDSTRTDT
    FROM
        QARD_ADENDUM
    GROUP BY
        ACCNBR) I ON
    A.ACCNBR = I.ACCNBR
LEFT JOIN FIN_RESTRUCT J ON
    A.ACCNBR = J.ACCNBR
LEFT JOIN HIST_OBJECT K ON
    A.ACCNBR = K.ACCNBR
LEFT JOIN OBJ_DEPRECIATION L ON
    K.OBJECTID = L.OBJECTID
LEFT JOIN BUSINESS_OBJ M ON
    K.OBJECTID = M.OBJECTID
LEFT JOIN V_MST_CIFTEMP N ON
    B.CIFID = N.CIFID
LEFT JOIN (
    SELECT
        CIFID,
        MAX(EMAIL) EMAIL,
        MAX(SEQNO) SEQNO
    FROM
        MST_CIFEMAIL
    GROUP BY
        CIFID) O ON
    B.CIFID = O.CIFID
LEFT JOIN CFG_PRDQARD P ON
    A.APPLID = P.APPLID
    AND A.PRODID = P.PRODID
LEFT JOIN V_XBRL_BILLPAYMENT3 Q ON
    A.ACCNBR = Q.ACCNBR
LEFT JOIN V_XBRL_EQRATEADENDUM R ON
    A.ACCNBR = R.ACCNBR
LEFT JOIN (
    SELECT
        COUNT(*) FREKTUNGGAKAN,
        ACCNBR
    FROM
        REF_BILLPAYMENT
    WHERE
        MNTHDT < (
        SELECT
            OPENDATE
        FROM
            CFG_SYS)
        AND (AMTPRCBILL + AMTINTBILL + AMTPENBILL)-(AMTPRCPAY + AMTINTPAY + AMTPENPAY) > 0
    GROUP BY
        ACCNBR ) FREK ON
    A.ACCNBR = FREK.ACCNBR
LEFT JOIN (
    SELECT
        ACCNBR,
        SUM(AMTPRCPAY) PCL,
        SUM(AMTDISCPAY) DISC,
        SUM(AMTINTPAY) MGN,
        SUM(MGNPAYPSAK) MGNPSAK,
        SUM(AMORATTRIBPAY) ADM
    FROM
        REF_BILLPAYMENT
    GROUP BY
        ACCNBR ) PDPT ON
    PDPT.ACCNBR = A.ACCNBR
WHERE
    A.ACCSTS NOT IN ('0',
    '9')
    OR (ACCSTS = 9
    AND STSDT = (
    SELECT
        OPENDATE
    FROM
        CFG_SYS))
UNION ALL
SELECT
    DISTINCT A.CRTDATE AS TBCRTDT,
    A.UPDDATE AS TBMDFDT,
    A.CIFID TBCIFID,
    A.ACCNBR TBACCNBR,
    COALESCE(A.IDFACILITY,
    A.ACCNBR) TBIDFACILITY,
    A.CIFNM,
    C.SURENM,
    B.FULLNM,
    C.ADDR,
    C.LASTEDUID,
    C.BRTPLACE,
    C.SEX,
    B.NPWP,
    (
    SELECT
        PARMNMOTH
    FROM
        CFG_PARM
    WHERE
        PARMID = C.OWNID
        AND PARMGRP = '824') TBOWNID,
    N.BANKREL,
    C.COUNTRYID,
    C.TYPEID,
    C.IDNBR,
    CAST(VARCHAR_FORMAT(C.BRTDT,
    'YYYY-MM-DD') AS VARCHAR(20)) AS TBBRTDT,
    C.MARRIAGEID,
    C.IDNBRCPL,
    C.CPLNAME,
    CAST(VARCHAR_FORMAT(C.CPLBRTHDT,
    'YYYY-MM-DD') AS VARCHAR(20)) AS TBCPLBRTHDT,
    C.DEALASST,
    C.LNGBMPK,
    C.PASSBMPK,
    C.MOTHRNM,
    B.BRANCHID,
    'C',
    NULL AS GRPUSH,
    --kolomnya belum ada
 A.ACCSTS,
    (
    SELECT
        PARMNMOTH
    FROM
        CFG_PARM
    WHERE
        PARMID = G.CTGBUSSXBRL
        AND PARMGRP = '810') AS TBCTGBUSSXBRL,
    (
    SELECT
        PARMNMOTH
    FROM
        CFG_PARM
    WHERE
        PARMID = G.CTGFRTFOLIO
        AND PARMGRP = '815') AS TBCTGFRTFOLIO,
    (
    SELECT
        PARMNMOTH
    FROM
        CFG_PARM
    WHERE
        PARMID = G.SRCFUND
        AND PARMGRP = '833') AS TBSMBRDN,
    (
    SELECT
        PARMNMOTH
    FROM
        CFG_PARM
    WHERE
        PARMID = N.CITYNM
        AND PARMGRP = '903') TBCITYNM,
    G.ECOSECXBRL TBECOSECXBRL,
    (
    SELECT
        PARMNMOTH
    FROM
        CFG_PARM
    WHERE
        PARMID = G.CTGBUSSXBRL
        AND PARMGRP = '810') AS TBCTGBUSSXBRLUMKM,
    '947' TBSRCFUND,
    COALESCE(P.TYPEINVEST,
    '1') AS TBTYPEINVEST,
    D.CERTNO,
    D.COMPNM,
    D.COMTYPE,
    D.ADDRBUILD,
    D.CERTNO,
    CAST(VARCHAR_FORMAT(D.DTBUILD,
    'YYYY-MM-DD') AS VARCHAR(20)) AS TBDTBUILD,
    N.LASTCERTNO,
    CAST(VARCHAR_FORMAT(N.LASTCERTDT,
    'YYYY-MM-DD') AS VARCHAR(20)) AS TBLASTCERTDT,
    N.NOTELP,
    N.NOHP,
    O.EMAIL,
    (
    SELECT
        PARMNM
    FROM
        CFG_PARM
    WHERE
        PARMID = N.KELNM
        AND PARMGRP = '906') TBKELNM,
    (
    SELECT
        PARMNM
    FROM
        CFG_PARM
    WHERE
        PARMID = N.KECNM
        AND PARMGRP = '904') TBKECNM,
    N.POSTALCODE,
    E.JOBID,
    E.COMNMJOB,
    E.ADDRJOB,
    C.AMTGRSSAL,
    C.MAINSALID,
    CASE
        WHEN C.INSURED IS NULL THEN 0
        ELSE C.INSURED
    END AS TBINSURED,
    COALESCE(C.LNGBMPK,
    D.LNGBMPK) TBLGRBMPK,
    D.GOPBLC,
    A.AMTPROJ,
    --khusus mst_financing
(
    SELECT
        MAX(FUNC) FUNC
    FROM
        MST_CIFSTAFF
    WHERE
        CIFID = A.CIFID) AS TBFUNC,
    (
    SELECT
        MAX(STSREC) STSREC
    FROM
        MST_CIFSTAFF
    WHERE
        CIFID = A.CIFID) AS TBSTSREC,
    100,
    (
    SELECT
        PARMNMOTH
    FROM
        CFG_PARM
    WHERE
        PARMID = G.KINDFINXBRL
        AND PARMGRP = '812') AS TBKINDFINXBRL,
    A.CONTRACTNO,
    CAST(VARCHAR_FORMAT(A.AGREEDT,
    'YYYY-MM-DD') AS VARCHAR(20)) AS TBAGREEAPRDT,
    I.NEWCONTRACTNO AS TBOLDCONTRACTNO,
    CAST(VARCHAR_FORMAT(I.OLDSTRTDT,
    'YYYY-MM-DD') AS VARCHAR(20)) AS TBOLDSTRTDT,
    CASE
        WHEN (
        SELECT
            COUNT(1)
        FROM
            QARD_ADENDUM
        WHERE
            ACCNBR = A.ACCNBR) = 0 THEN '0'
        ELSE (
        SELECT
            COUNT(1)
        FROM
            QARD_ADENDUM
        WHERE
            ACCNBR = A.ACCNBR)
    END AS TBBR,
    CAST(VARCHAR_FORMAT(A.OPENDT,
    'YYYY-MM-DD') AS VARCHAR(20)) AS TBOPENDT,
    CAST(VARCHAR_FORMAT(A.STRTDT,
    'YYYY-MM-DD') AS VARCHAR(20)) AS TBSTRTDT,
    CAST(VARCHAR_FORMAT(A.DUEDT,
    'YYYY-MM-DD') AS VARCHAR(20)) AS TBDUEDT,
    CASE
        WHEN A.APPLID = '09' THEN 'B'
        WHEN A.APPLID = '08' THEN 'S'
        WHEN A.APPLID IN ('05',
        '06',
        '11') THEN 'P'
        ELSE NULL
    END TBSKMPBY,
    CASE
        WHEN A.APPLID = '09'
        AND P.FINTYPE = '1'
        AND P.SHAREDID = '000' THEN '025'
        WHEN A.APPLID = '09'
        AND P.FINTYPE = '1' THEN '020'
        WHEN A.APPLID = '09'
        AND P.FINTYPE = '2'
        AND P.STSMUTANAQISAH = '1' THEN '035'
        WHEN A.APPLID = '09'
        AND P.FINTYPE = '2' THEN '030'
        WHEN A.APPLID = '08'
        AND P.FINTYPE = '3' THEN '040'
        WHEN A.APPLID = '08'
        AND P.FINTYPE = '4' THEN '045'
        WHEN A.APPLID = '08'
        AND P.KINDIJR = '2' THEN '069'
        WHEN A.APPLID = '05' THEN '070'
        WHEN A.APPLID = '06' THEN '080'
        WHEN A.APPLID = '11' THEN '100'
        ELSE NULL
    END AS TBJNSAKAD,
    CASE
        WHEN A.APPLID IN ('09',
        '11') THEN 'NMT'
        ELSE NULL
    END AS TBMTDBGHSL,
    --JIKA MUDHRABAH 'NMT' ELSE NULL
    --CAST(VARCHAR_FORMAT(A.AGREEAPRDT, 'YYYY-MM-DD') AS VARCHAR(20)) AS TBTGLCAIR,
(
    SELECT
        CAST(VARCHAR_FORMAT(MAX(TXDATE),
        'YYYY-MM-DD') AS VARCHAR(20)) MAX_TXDATE
    FROM
        HIST_TX_PBY HTP
    WHERE
        HTP.TXCODE = 199
        AND HTP.ACCNBR = A.ACCNBR) AS TBTGLCAIR,
    VARCHAR_FORMAT(ROUND(A.EQRATE, 2),
    '990.99') TBEQRATE,
    A.RATIORBH,
    G.TYPEFINXBRL,
    G.TYPEUSEDXBRL,
    (
    SELECT
        PARMNMOTH
    FROM
        CFG_PARM
    WHERE
        PARMID = G.ORIUSEDXBRL
        AND PARMGRP = '830') TBORIUSEDXBRL,
    P.CCYID,
    G.GVRMENTPRGM,
    G.SKUR,
    G.LOCXBRL,
    CASE
        WHEN A.APPLID = '09' THEN 4
        WHEN A.APPLID IN ('05',
        '06',
        '07') THEN 3
        WHEN A.APPLID IN ('08',
        '11') THEN 5
        ELSE NULL
    END TBDefault,
    VARCHAR_FORMAT(COALESCE(ROUND(R.OLDEQRATE, 2),
    ROUND(A.EQRATE, 2)),
    '990.99') TBEQRATEAWL,
    VARCHAR_FORMAT(ROUND(A.EQRATE, 2),
    '990.99') TBEQRATEBLN,
    A.QUALRPT,
    COALESCE(H.AMOUNT,
    A.PLAFOND) TBPLAFOND,
    A.PLAFOND,
    --data diturunkan berdasarkan akad (bukan hanya dari table Qardh)" amtbal ato plafond
 0 AMTBAL,
    (
    SELECT
        PARMNMOTH
    FROM
        CFG_PARM
    WHERE
        PARMID = G.RATINGINST
        AND PARMGRP = '816') TBRATINGINST,
    (
    SELECT
        PARMNMOTH
    FROM
        CFG_PARM
    WHERE
        PARMID = G.RATINGVAL
        AND PARMGRP = '301') TBRATINGVAL,
    CAST(VARCHAR_FORMAT(G.RATINGDT,
    'YYYY-MM-DD') AS VARCHAR(20)) AS TBRATINGDT,
    A.TKOVR AS TBTKOVR,
    --khusus mst_financing
 A.QUALCD TBQUALRPTKD,
    CAST(VARCHAR_FORMAT(A.QUALDT,
    'YYYY-MM-DD') AS VARCHAR(20)) AS TBQUALDT,
    G.PUJAMIN,
    G.SBBMCT,
    H.PERIOD AS TBPERIODFIN,
    CASE
        WHEN A.APPLID = '08' THEN A.AMTMARGIN
        ELSE 0
    END AS TBAMTMARGIN,
    CASE
        WHEN A.APPLID = '08' THEN L.AKMDEPR
        ELSE 0
    END AS TBAKMDEPR,
    CASE
        WHEN A.APPLID = '08' THEN A.AMTCKPN
        ELSE 0
    END AS TBPPAP,
    A.ADVANCE,
    --khusus mst_financing
 A.PLAFOND,
    0,
    A.AMTBAL,
    0,
    CASE
        WHEN A.APPLID = '05' THEN A.AMTBAL - (A.TOTATTRIB - A.ACUMPAYATTRIB)
        ELSE A.AMTBAL
    END TBHP,
    --sisa_margin dari mana
 A.AMTMARGIN - A.ACUMPAYMGN TBMRGTGH,
    CASE
        WHEN A.ACCSTS = 9 THEN 0
        ELSE A.AMTBAL
    END TBAMTBAL,
    CASE
        WHEN A.ACCSTS = 9 THEN 0
        ELSE A.PLAFOND + A.ADVANCE
    END TBAMTBALIDR,
    0 TBAMTBALVLS,
    A.ACUMACCRU + A.ACUMPYAD AS TBACUMACCRU,
    CASE
        WHEN A.ACCSTS = 9 THEN 0
        ELSE A.AMTBAL
    END,
    A.PENALTY TBDENDA,
    --diqardh blm ada kolom penalty
 A.AMTPCLOUT,
    A.AMTMGNOUT,
    A.DAYPASTDUE,
    A.DAYPASTDUEPCL,
    A.DAYPASTDUEMGN,
    COALESCE(FREK.FREKTUNGGAKAN,
    0) AS TBFRQTGK,
    --(count)
 A.AMTCKPN,
    J.RESTRUCTWAY,
    J.AMTLOSS,
    --blm ada kolomny
 A.RESTRUCTCOUNT,
    CAST(VARCHAR_FORMAT(J.RESTRUCTDT,
    'YYYY-MM-DD') AS VARCHAR(20)) AS TBRESTRUCTDTAWL,
    CAST(VARCHAR_FORMAT(A.RESTRUCTDT,
    'YYYY-MM-DD') AS VARCHAR(20)) AS TBRESTRUCTDTAHR,
    H.STSCOND TBACCSTSKD,
    CAST(VARCHAR_FORMAT(A.STSDT,
    'YYYY-MM-DD') AS VARCHAR(20)) AS TBACCSTSTGL,
    A.ACCNBR,
    (
    SELECT
        PARMNMOTH
    FROM
        CFG_PARM
    WHERE
        PARMID = M.ASSETTYPEXBRL
        AND PARMGRP = '817') AS TBASSETTYPEXBRL,
    CAST(VARCHAR_FORMAT(K.STRDT,
    'YYYY-MM-DD') AS VARCHAR(20)) AS TBSTRTDTASET,
    M.CCYID,
    K.BOOKVALUE,
    L.OBJECTAGE,
    CASE
        WHEN A.APPLID = '08' THEN L.DEPRMTD
        ELSE 0
    END AS TBDEPRMTD,
    CASE
        WHEN A.APPLID IN ('05',
        '08') THEN A.SELLPRICE
        ELSE A.PLAFOND
    END AS TBNILKTK,
    CASE
        WHEN A.APPLID = '09' THEN H.FLEXAMT
        ELSE 0
    END AS TBFLEXAMTCOM,
    0 AS TBFLEXAMTUNCOM,
    CASE
        WHEN A.PLAFOND < A.FLEXAMT THEN 0
        ELSE A.PLAFOND
    END AS TBAGUNANKRD,
    A.FLEXAMT TBAGUNANLGRTRK,
    CASE
        WHEN A.QUALCD = 1 THEN A.AMTCKPNPSAK
        ELSE 0
    END AS TBAMTCKPNPSAKB,
    CASE
        WHEN (A.QUALCD = 2
        OR A.QUALCDREST = 1) THEN A.AMTCKPNPSAK
        ELSE 0
    END AS TBAMTCKPNPSAKKB,
    CASE
        WHEN (A.QUALCD IN (3,
        4,
        5)
        OR A.QUALCDREST = 2) THEN A.AMTCKPNPSAK
        ELSE 0
    END AS TBAMTCKPNPSAKTB,
    CAST(VARCHAR_FORMAT(H.DUEDT,
    'YYYY-MM-DD') AS VARCHAR(20)) AS TBFREKADDJT,
    A.AMTBAL TBAMTASL,
    H.NOTE TBNOTE,
    NULL AS TBDEPRDT,
    A.SGMNID TBSGMNID,
    H.CONTRACTNO AS TBCONTRACTNOFAS,
    '' AS TBOTHDEST,
    '' AS TBOTHSRC,
    '' AS TBTYPEREP,
    A.AMTBAL AS TBOSTBAL,
    A.SGMNID AS TBSEGMENT,
    CASE
        WHEN A.APPLID = '05' THEN A.ACUMPAYMGNPSAK - A.ACUMPAYMGN
        ELSE 0
    END AS TBMGNEFCTV,
    CASE
        WHEN A.APPLID = '05' THEN A.TOTATTRIB - A.ACUMPAYATTRIB
        ELSE 0
    END AS TBAMORATRIB,
    CASE
        WHEN A.APPLID = '05' THEN A.ACUMACCRUPSAK + A.ACCRUPSAKOUT
        ELSE 0
    END AS TBACUMACRUPSAK,
    A.ACUMAMOR + A.AMOROUT AS TBACUMACRUATRIB,
    PDPT.DISC AS TBPDPTDISC,
    PDPT.ADM AS TBPDPTADM,
    A.ACUMPAYMGN AS TBPDPTMGN,
    CASE
        WHEN A.APPLID = '05' THEN PDPT.MGNPSAK - PDPT.MGN
        ELSE 0
    END AS TBPDPTMGNPSAK,
    0 AS TBPDPTMGNWO,
    0 AS TBPDPTPCLWO
FROM
    MST_FINANCING A
LEFT JOIN MST_CIF B ON
    A.CIFID = B.CIFID
LEFT JOIN MST_CIFPERSNL C ON
    B.CIFID = C.CIFID
LEFT JOIN MST_CIFCOM D ON
    B.CIFID = D.CIFID
LEFT JOIN (
    SELECT
        DISTINCT CIFID,
        MAX(JOBID) JOBID,
        MAX(COMNMJOB) COMNMJOB,
        MAX(ADDRJOB) ADDRJOB,
        MAX(DTCRT) DTCRT
    FROM
        MST_CIFJOB
    WHERE
        AKTIFJOB = 1
    GROUP BY
        CIFID) E ON
    B.CIFID = E.CIFID
LEFT JOIN CFG_LBUSID G ON
    A.ACCNBR = G.ACCNBR
LEFT JOIN FIN_FACILITY H ON
    A.IDFACILITY = H.IDFACILITY
LEFT JOIN (
    SELECT
        ACCNBR,
        NEWCONTRACTNO,
        MAX(OLDSTRTDT) OLDSTRTDT
    FROM
        FIN_ADENDUM
    GROUP BY
        ACCNBR,
        NEWCONTRACTNO) I ON
    A.ACCNBR = I.ACCNBR
LEFT JOIN FIN_RESTRUCT J ON
    A.ACCNBR = J.ACCNBR
LEFT JOIN HIST_OBJECT K ON
    A.ACCNBR = K.ACCNBR
LEFT JOIN OBJ_DEPRECIATION L ON
    K.OBJECTID = L.OBJECTID
LEFT JOIN BUSINESS_OBJ M ON
    K.OBJECTID = M.OBJECTID
LEFT JOIN V_MST_CIFTEMP N ON
    B.CIFID = N.CIFID
LEFT JOIN (
    SELECT
        CIFID,
        MAX(EMAIL) EMAIL,
        MAX(SEQNO) SEQNO
    FROM
        MST_CIFEMAIL
    GROUP BY
        CIFID) O ON
    B.CIFID = O.CIFID
LEFT JOIN CFG_PRDFIN P ON
    A.APPLID = P.APPLID
    AND A.PRODID = P.PRODID
LEFT JOIN V_XBRL_BILLPAYMENT3 Q ON
    A.ACCNBR = Q.ACCNBR
LEFT JOIN V_XBRL_EQRATEADENDUM R ON
    A.ACCNBR = R.ACCNBR
LEFT JOIN (
    SELECT
        COUNT(*) FREKTUNGGAKAN,
        ACCNBR
    FROM
        REF_BILLPAYMENT
    WHERE
        MNTHDT < (
        SELECT
            OPENDATE
        FROM
            CFG_SYS)
        AND (AMTPRCBILL + AMTINTBILL + AMTPENBILL)-(AMTPRCPAY + AMTINTPAY + AMTPENPAY) > 0
    GROUP BY
        ACCNBR ) FREK ON
    A.ACCNBR = FREK.ACCNBR
LEFT JOIN (
    SELECT
        ACCNBR,
        SUM(AMTPRCPAY) PCL,
        SUM(AMTDISCPAY) DISC,
        SUM(AMTINTPAY) MGN,
        SUM(MGNPAYPSAK) MGNPSAK,
        SUM(AMORATTRIBPAY) ADM
    FROM
        REF_BILLPAYMENT
    GROUP BY
        ACCNBR ) PDPT ON
    PDPT.ACCNBR = A.ACCNBR
WHERE
    A.ACCSTS NOT IN ('0',
    '9')
    OR (ACCSTS = 9
    AND STSDT = (
    SELECT
        OPENDATE
    FROM
        CFG_SYS))